parameters:
  - name: scalar
    type: string
    default: defaultscalarvalue
  - name: number
    type: number
    default: 0
  - name: boolean
    type: boolean
    default: true
  - name: object
    type: object
    default:
      - key1: value1
      - key2: value2
  - name: storageContainerPrefix
    type: string
    default: ''

variables:
  - name: scalar
    value: ${{ parameters.scalar  }}
  - name: number
    value: ${{ parameters.number  }}
  - name: boolean
    value: ${{ parameters.boolean }}
  - name: object
    value: ${{ convertToJson(parameters.object)  }}
  - ${{ if eq(length(parameters.storageContainerPrefix), 0) }}:
    - name: storageContainerPrefix
      value: ''
  - ${{ if ne(length(parameters.storageContainerPrefix), 0) }}:
    - name: storageContainerPrefix
      value: --destination-path ${{ parameters.storageContainerPrefix }}

stages:
  - stage: Test
    jobs:
    - job: Introspection
      displayName: Display parameters and variables
      steps:
        - task: Bash@3
          displayName: Show parameters
          inputs:
            targetType: filePath
            filePath: scripts/show_parameters.sh
          env:
            ${{ each parameter in parameters }}:
              parameter_${{ parameter.key }}: "|${{ convertToJson(parameter.value) }}|"
    - job: Testing
      displayName: Testing
      workspace:
        clean: all
      steps:
#        - ${{ each parameter in parameters }}:
#          - script: echo "${{ parameter.key }} == |${{ convertToJson(parameter.value) }}|"
        - task: Bash@3
          displayName: show fs
          condition: always()
          inputs:
            targetType: inline
            script: |
              pwd && ls -al
        - task: AzureCLI@2
          displayName: deploy site
          inputs:
            azureSubscription: serviceconnection
            scriptType: pscore
            scriptLocation: inlineScript
            inlineScript: |
              echo "storageContainerPrefix == $(storageContainerPrefix)"
              az storage blob upload-batch --source site --destination '$web' --account-name leriksentesting --account-key 'kVN5xA12KKOFmJfF/KcnBw2pISB7fiqqP/KAfKE5FNiF7fghJkP4irJOHQwgYVqKcwpEaIib8aF6NRbqxTkBtg==' $(storageContainerPrefix)
