parameters:
  - name: scalar
    type: string
    default: defaultscalarvalue
  - name: number
    type: number
    default: 0
  - name: boolean
    type: boolean
    default: true
  - name: object
    type: object
    default:
      - key1: value1
      - key2: value2
  - name: storageContainerPrefix
    type: string
    default: ''

jobs:
  - job: Testing
    displayName: Testing
    workspace:
      clean: all
    variables:
      scalar:  ${{ parameters.scalar  }}
      number:  ${{ parameters.number  }}
      boolean: ${{ parameters.boolean }}
      object:  ${{ convertToJson(parameters.object)  }}
    steps:
      - checkout: self
      - task: Bash@3
        displayName: Display env
        condition: always()
        inputs:
          targetType: inline
          script: |
            env
#      - task: Bash@3
#        displayName: Display vars
#        condition: always()
#        inputs:
#          targetType: inline
#          script: |
#            echo "scalar  == ${{ variables.scalar  }}"
#            echo "number  == ${{ variables.number  }}"
#            echo "boolean == ${{ variables.boolean }}"
#            echo "object  == ${{ variables.object  }}"
#      - task: Bash@3
#        displayName: Display params
#        condition: always()
#        inputs:
#          targetType: inline
#          script: |
#            echo "scalar  == ${{ parameters.scalar                }}"
#            echo "number  == ${{ parameters.number                }}"
#            echo "boolean == ${{ parameters.boolean               }}"
#            echo "object  == ${{ convertToJson(parameters.object) }}"

      - task: AzureCLI@2
        displayName: deploy site
        inputs:
          azureSubscription: serviceconnection
          scriptType: pscore
          scriptLocation: inlineScript
          inlineScript: |
            az --version
            az storage blob upload-batch --source site --destination '$web' --account-name leriksentesting --account-key 'kVN5xA12KKOFmJfF/KcnBw2pISB7fiqqP/KAfKE5FNiF7fghJkP4irJOHQwgYVqKcwpEaIib8aF6NRbqxTkBtg==' --destination-path '$(storageContainerPrefix)'
