name: $(BuildDefinitionName).$(Build.Reason)$(Rev:.r)

trigger: none

pr: none

pool:
  vmImage: ubuntu-latest

extends:
  template: template/testing.yml
  parameters:
    storageContainerPrefix: here