name: $(BuildDefinitionName).$(Build.Reason)$(Rev:.r)

trigger: none

pr: none

steps:
  - script: pwd && ls -al
#  - template: template/npm.yml
#    parameters:
#      - basePath: '.'
#      - version: '1.1.1'

#extends:
#  template: template/testing.yml
#  parameters:
#    storageContainerPrefix: here